export const Colors = {
  transparent: 'transparent',
  white: '#fff',
  black: '#000',
  lessWhite: '#ECEEF3',
  lessBlack: '#2A2929',
  gray: '#454545',
  headerInputOutline: '#4F4F4F',
  headerInputActiveOutline: '#303030',
  topContainerBackground: '#82CAFE',
  topContainerGradient: '#7EAEFD',
  weatherTimelyCardBackground: '#5FBDF8',
  weatherTimelyCardGradient: '#3183DB',
  weatherTimelyCardInactiveGradient: '#A5D7F7',
  weatherTimelyCardInactiveBackground: '#D4EEFF',
  weatherDetailsCardGradient: '#52A4F1',
  inactiveWeatherDetailsCardText: '#7A7A7A',
  weatherDetailsIcon: '#E3E3E3',
  textLink: '#54B4E4',
  dailyWeatherCardBackground: '#D5EAFD',
  dailyWeatherCardSelectedBackground: '#B7DCFF',
  overlaySpinnerBackground: 'rgba(0, 0, 0, 0.7)',
  errorText: '#FF4848',
};
